### ISSUE TITLE
Spinlock should usleep

### ISSUE THREAD

**Issue by mevdschee** [1ma/RedisSessionHandler#1]
Great initiative! I think your spinlock should use a usleep of 150 ms.

https://github.com/1ma/RedisSessionHandler/blob/master/RedisSessionHandler.php#L164

In order not to stress the CPU too much. See also:

https://github.com/php-memcached-dev/php-memcached/blob/master/php_memcached_session.c#L162

and

https://github.com/snc/SncRedisBundle/blob/master/Session/Storage/Handler/RedisSessionHandler.php#L146

I hope this helps.

**Comment by 1ma** [comment]
Yes it does, thank you Maurits.

In order to assess the difference that usleep could make I've cranked up the [number of concurrent requests per test](https://github.com/1ma/RedisSessionHandler/blob/master/tests/e2e/ConcurrentTest.php#L11) to 10,000 and tweaked FPM as a static pool of 8 worker processes (the number of cores my machine has). These are the results I am seeing when I run the "locking intensive" test with these settings:

## empty loop
```bash
marcel@powerbase:~/workspace/RedisSessionHandler$ docker exec -it tests_testrunner_1 php vendor/bin/phpunit --filter ConcurrentTest::testAuthenticatedRequests
PHPUnit 4.8.31 by Sebastian Bergmann and contributors.

.

Time: 8.52 seconds, Memory: 8.00MB

OK (1 test, 2 assertions)
```
![no-usleep](http://i.imgur.com/RdGzHJW.png)

## usleep of 150ms
```bash
marcel@powerbase:~/workspace/RedisSessionHandler$ docker exec -it tests_testrunner_1 php vendor/bin/phpunit --filter ConcurrentTest::testAuthenticatedRequests
PHPUnit 4.8.31 by Sebastian Bergmann and contributors.

.

Time: 8.19 seconds, Memory: 8.00MB

OK (1 test, 2 assertions)
```
![150ms-usleep](http://i.imgur.com/bOPGQA9.png)

That 0.33s speedup might or might not be a fluke but in the second test the CPUs are clearly less busy, so I'll make that change.

Thanks again. I'll wait for 24-48h hours to see if any other immediate issues come up, then I'll tag a 0.9.1 release.

**Comment by mevdschee** [comment]
Note that the average response times will go up, due to this change. I think that is acceptable, but the back-off algorithm (double wait time every iteration) from memcached should minimize that, see:

https://github.com/php-memcached-dev/php-memcached/blob/master/php_memcached_session.c#L163

You may not program C, but I do and we could (try to) fix this problem in phpredis together, if you want that.

**Comment by 1ma** [comment]
I could years ago, and I still can understand (most of) it. Nevertheless I don't feel confident _at all_ fiddling with code so widely deployed.

Still, as I said in the phpredis thread, it would be 1000x better to fix these issues there and be done with a simple update from your package manager of choice. So if you want to try I'll at least review the patches, for what little this is worth...

**Comment by mevdschee** [comment]
I'm not at all proficient in Zend specific stuff, so for me it not easy either. Nevertheless the code that needs to be added is limited, so I guess I could (at least try).

Did you see?

https://github.com/snc/SncRedisBundle/blob/master/Session/Storage/Handler/RedisSessionHandler.php

How does your code compare to it?

**Comment by mevdschee** [comment]
Did you see this implementation?

https://github.com/snc/SncRedisBundle/blob/master/Session/Storage/Handler/RedisSessionHandler.php

Maybe there are things to improve in either one.

**Comment by 1ma** [comment]
Yes, though I believe this handler has some advantages, namely:
* It supports ["strict mode"](http://php.net/manual/en/session.configuration.php#ini.session.use-strict-mode). AFAIK no other handler does, barring the native `files`.
* It's a standalone class, not part of a Symfony bundle (it pulls down the FrameworkBundle and all its dependencies, even if these aren't ultimately used by the session handler).
* The testing approach I chose is more sound for this kind of project ([system testing](https://github.com/1ma/RedisSessionHandler/blob/master/tests/e2e/BasicTest.php) vs [unit testing](https://github.com/snc/SncRedisBundle/blob/master/Tests/Session/Storage/Handler/RedisSessionHandlerTest.php)).

However snc's session handler is mature and popular, so it has seen some shit. It surely handles all sorts of details and corner cases that I haven't thought about, like the one just discussed above.

**Comment by 1ma** [comment]
Finally found some time to work into the project again. Since you predicted that avg response times would go up I also ran a couple more benchmarks† to measure that:

## empty loop
```bash
$ hey -n 10000 -H "Cookie: PHPSESSID=inbqgmgqhrb9egckpaoj1b246f2ecl5fomfuonpn7o2dmhol8ug1;" http://localhost/visit-counter.php

Summary:
  Total:	9.4222 secs
  Slowest:	0.0782 secs
  Fastest:	0.0178 secs
  Average:	0.0470 secs
  Requests/sec:	1061.3187

Status code distribution:
  [200]	10000 responses

Response time histogram:
  0.018 [1]	|
  0.024 [5]	|
  0.030 [6]	|
  0.036 [7]	|
  0.042 [1391]	|∎∎∎∎∎∎∎∎∎∎
  0.048 [5394]	|∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
  0.054 [2135]	|∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
  0.060 [744]	|∎∎∎∎∎∎
  0.066 [253]	|∎∎
  0.072 [56]	|
  0.078 [8]	|

Latency distribution:
  10% in 0.0414 secs
  25% in 0.0433 secs
  50% in 0.0459 secs
  75% in 0.0492 secs
  90% in 0.0543 secs
  95% in 0.0583 secs
  99% in 0.0640 secs
```

## back-off'd locking
```bash
$ hey -n 10000 -H "Cookie: PHPSESSID=inbqgmgqhrb9egckpaoj1b246f2ecl5fomfuonpn7o2dmhol8ug1;" http://localhost/visit-counter.php

Summary:
  Total:	10.6037 secs
  Slowest:	0.5691 secs
  Fastest:	0.0020 secs
  Average:	0.0523 secs
  Requests/sec:	943.0659

Status code distribution:
  [200]	10000 responses

Response time histogram:
  0.002 [1]	|
  0.059 [9102]	|∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
  0.115 [873]	|∎∎∎∎
  0.172 [6]	|
  0.229 [11]	|
  0.286 [0]	|
  0.342 [3]	|
  0.399 [0]	|
  0.456 [3]	|
  0.512 [0]	|
  0.569 [1]	|

Latency distribution:
  10% in 0.0461 secs
  25% in 0.0487 secs
  50% in 0.0516 secs
  75% in 0.0547 secs
  90% in 0.0582 secs
  95% in 0.0622 secs
  99% in 0.0728 secs
```

Throughput is roughly the same and response times are much more consistent but the slowest ones are now an order of magnitude slower (!). Still, I went ahead with these changes because I think the CPU savings are worth it.

*† FTR, on a much less powerful machine than last time.*
