### ISSUE TITLE
does not support save_path parameters

### ISSUE THREAD

**Issue by marcing** [1ma/RedisSessionHandler#2]
Hi,

The handler only works with save_path which does not contain any parameters like timeout, database, auth.

Open method should be something like:

public function open($save_path, $name)
    {
        $save_path = parse_url($save_path);
        $timeout = 0;
        $database = 0;
        $auth = null;

        if(isset($save_path['query']))
        {
            parse_str($save_path['query']);
            $timeout = floatval($timeout);
            $database = intval($database);
        }

        $result = $this->redis->connect($save_path['host'], $save_path['port'], $timeout);
        if(!$result)
        {
            return false;
        }

        if($auth !== null)
        {
            $result = $this->redis->auth($auth);
            if(!$result)
            {
                return false;
            }
        }

        if($database > 0)
        {
            $result = $this->redis->select($database);
            if(!$result)
            {
                return false;
            }
        }

        return true;
    }

**Comment by 1ma** [comment]
I'll implement `timeout`, `prefix`, `auth` and `database`.

Does anyone here uses `weight` with multiple backends? I'm not keen to do this one because I'd have to come up with an algorithm to ensure sticky sessions (i.e. a given ID is always stored in the same backend).

PD For reference, [here is the complete list of parameters](https://github.com/phpredis/phpredis#php-session-handler) from the original handler.

**Comment by marcing** [comment]
I do not need the weight parameter. I am fine with proposed set.

**Comment by 1ma** [comment]
Implemented in v0.9.2. The README.md file now has a list of the available options and some configuration examples.
