### ISSUE TITLE
[Proposal] Sessions without cookie

### ISSUE THREAD

**Issue by jorge07** [1ma/RedisSessionHandler#4]
I was thinking about the issue https://github.com/1ma/RedisSessionHandler/issues/3. 

The sessions are stored in a cookie in the client for authentication propose.  But I use to work with JWT instead and I wanna be able to use a JWT for the session authentication. 
 
Example:

`eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXNzaW9uSWQiOiJramhiazIzajFodmhvbW9tYXJjZWwxMjMxMmluMTMiLCJuYW1lIjoiVmljdG9yIFJpb3MiLCJyb2xlcyI6WyJsZWdhY3kiXX0.M6vwdTwaXMFrYphDbytCzRwk2ONIYcXaV960oxBDyUs`

You can use the JWT token as sessionId or like in this token add a a sessionId inside.
This mechanism can give me the possibility of expire a valid JWT token, for example.

The handler will require some modifications to allow custom `SessionAware` objects and a default `CookieSessionAware`.

That do you think? Make sense to you?

**Comment by 1ma** [comment]
If I understand correctly, you want to "marry" JWT tokens to PHP sessions. So that a JWT would contain all the data that would normally be stored in Redis or local files, and when an HTTP request hits the backend, `session_start()` would take care of moving the data to the $_SESSION superglobal (and moving it back when the session ends).

Yes, I believe this makes sense, but it's way outside the scope of a Redis session handler.

You might want to take a look at the [psr7sessions](https://github.com/psr7-sessions) projects, by Ocramius & friends. [This one](https://github.com/psr7-sessions/storageless-native-handler) could be exactly what you want. Also read the [known issues](https://github.com/psr7-sessions/storageless/blob/master/docs/limitations.md), even if you don't like their implementation and want to make your own they'd still apply.

PD LMAO at your JWT example :laughing:

**Comment by 1ma** [comment]
O hey wait, if you send the whole JWT in a cookie instead of the `Authorization` header you would actually be able to invalidate specific sessions:

```
(Request headers)
Cookie: PHPSESSID=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXNzaW9uSWQiOiJramhiazIzajFodmhvbW9tYXJjZWwxMjMxMmluMTMiLCJuYW1lIjoiVmljdG9yIFJpb3MiLCJyb2xlcyI6WyJsZWdhY3kiXX0.M6vwdTwaXMFrYphDbytCzRwk2ONIYcXaV960oxBDyUs; ...other cookies
```
...with the usual method:
```
(Response headers)
Set-Cookie: PHPSESSID=deletednaogoaway; expires=Thu, 01-Jan-1970 00:00:00 GMT; Max-Age=0
```

Of course, you'd still need to keep in mind that cURL clients and the like would do what they want, and plan for that. But regular browsers run by regular people would abide.

Edit: related http://stackoverflow.com/questions/686217/maximum-on-http-header-values (since all cookies sent on a given request share the same header)

**Comment by jorge07** [comment]
I wanna still using `Authorization` header. The main reason its because JWT signed with cert are lot bigger than normal cookie and the second one it's to be client agnostic and use the standard `Authorization` header. In symfony right now you need to set `stateless` to true to invalidate sessions when using JWT tokens. I wanna be able to logout a user by sending his JWT. Thats not possible with psr7 sessions: https://github.com/psr7-sessions/storageless/blob/master/docs/limitations.md#sessions-cannot-be-invalidated
